// Generated by CoffeeScript 1.6.3
var app, http, path;

path = require('path');

http = require('http');

app = http.createServer(function(req, res) {
  return console.log(req.url);
});

app.listen(3100);
